"""empty message

Revision ID: 2e3bc9793d77
Revises: 
Create Date: 2018-05-16 18:06:21.526417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3bc9793d77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserCode', sa.String(length=64), nullable=True),
    sa.Column('Password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users2_UserCode'), 'users2', ['UserCode'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users2_UserCode'), table_name='users2')
    op.drop_table('users2')
    # ### end Alembic commands ###
